FROM brendanburns/php

ADD index.php /var/www/index.php
ADD controllers.js /var/www/controllers.js
ADD index.html /var/www/index.html
ADD suse-logo.png /var/www/suse-logo.png
ADD pokemon.png /var/www/pokemon.png

CMD /run.sh
